### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by yboujraf** [hvianna/audioMotion-analyzer#1]
Dear @hvianna 

Good job for this repository.

Do you think you will do :

- Vu and ppm metering :

![whats the difference between PPM and VU meter](https://user-images.githubusercontent.com/6151258/74634345-f0b18780-5163-11ea-90cf-4fee70dc599b.jpg)

- loudness metering :

![loudness](https://user-images.githubusercontent.com/6151258/74634356-f8712c00-5163-11ea-87b6-dbe296208473.jpg)

- correlation metering :

![ppm correlation](https://user-images.githubusercontent.com/6151258/74634440-26567080-5164-11ea-9711-e85e43ee2da0.png)

I have a data model where I can stream all the data from an audio console :

```
                        {
                            "number": 3,
                            "path": "2.20.3",
                            "_subscribers": {},
                            "identifier": "Main Level",
                            "description": "Main Level",
                            "value": 480,
                            "minimum": -4096,
                            "maximum": 480,
                            "access": 1,
                            "format": "%8.2f°\ndB",
                            "enumeration": "",
                            "factor": 32,
                            "isOnline": true,
                            "default": -1024,
                            "type": 1,
                            "streamIdentifier": 281904
                        }
```

Do you think I could link your audio motion analyser with my data model ?

Best Regards,
Youssef

**Comment by hvianna** [comment]
Hello!

I have no plans to add volume meters at the moment. Perhaps [this project](https://esonderegger.github.io/web-audio-peak-meter/) does what you're looking for?

> Do you think I could link your audio motion analyser with my data model ?

My code works only with files and streams supported by the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), as it uses the API's built-in objects and functions to read the audio and extract the frequency information.

Using your data stream would require a custom parser and FFT implementation to generate the data needed by audioMotion.
