### ISSUE TITLE
AudioMotion and Pizzicato

### ISSUE THREAD

**Issue by franck34** [hvianna/audioMotion-analyzer#10]
Hi

audioMotion demos are impressive !

I'm trying to use both https://github.com/alemangui/pizzicato and audioMotion.

I've tested many things (i'm completely new with Web Audio). No luck. My last try was 

```
const el = document.getElementById('container');
const audioMotion = new AudioMotionAnalyzer(el, {});
audioMotion.connectInput(Pizzicato.context.destination);

const soundPath = '/path/to/sound.ogg';
const mySound = new Pizzicato.Sound(soundPath, () => {
    mySound.play();
});
```

Error
```
Uncaught DOMException: Failed to execute 'connect' on 'AudioNode': output index (0) exceeds number of outputs (0)
```

I have no idea how to "connect" Pizzicato with AudioMotion :(

Any help is welcome, thank you !

**Comment by hvianna** [comment]
Hello!

Audio nodes must be created in the same audio context so they can be connected to each other. You can pass Pizzicato's context to the audioMotion-analyzer constructor, like so:

```
const el = document.getElementById('container');
const audioMotion = new AudioMotionAnalyzer( el, {
    audioCtx: Pizzicato.context
});
```

Then use the `getInputNode()` method to connect Pizzicato objects to audioMotion, like so:

```
const soundPath = '/path/to/sound.ogg';
const mySound = new Pizzicato.Sound( soundPath, () => {
    audioMotion.connectInput( mySound.getInputNode() );
    mySound.play();
});
```

Live example: https://codesandbox.io/s/9y6qb  (you may need to click the canvas on first run to unlock the audio context)

**Comment by franck34** [comment]
:heart: :heart: :heart: :heart: :heart:

" My God, it's full of stars! "
