### ISSUE TITLE
Option to bypass connecting the output

### ISSUE THREAD

**Issue by evoyy** [hvianna/audioMotion-analyzer#13]
It seems that audioMotion is intended to be a permanent component of the Web Audio signal path, and one instance is created and kept for the lifetime of the app. In my case, I already have a player with its own AudioContext, and input and output nodes, and I want to create an audioMotion instance on demand in a modal window, so that when the modal is opened, I connect the output node from my player as the source for audioMotion to analyze the signal. The problem is that audioMotion is connecting its own output to the same AudioContext destination, so both my player, and audioMotion, are sending their outputs to the speakers together, resulting in boosted volume:

````
(source) ---> player ---> output ---> speakers
                            |
                            +---> analyzer ---> output ---> speakers
````

As a workaround I can set `audioMotion.volume = 0` after creating an instance:

````javascript
    const audioMotion = new AudioMotionAnalyzer(container, {
        audioCtx: myApp.player.audioContext,
        source: myApp.player.outputNode,
    });

    audioMotion.volume = 0;
````

Can I suggest adding a boolean `connectOutput` (default: true) option in the constructor to allow for bypassing the connecting of the output?

**Comment by hvianna** [comment]
Thanks for the suggestion.

When I was testing the [`disconnectOutput()`](https://github.com/hvianna/audioMotion-analyzer#disconnectoutput-node-) method (which you can call with no parameters to disconnect audioMotion from the speakers) I realized that Chromium browsers stop generating analyzer data when audioMotion's output is disconnected from the audioContext destination. 

Here's a quick pen to demonstrate the issue -> https://codepen.io/hvianna/pen/vYgGwGz

It works fine on Firefox though, so maybe it's some sort of optimization in Chromium's WebAudio implementation, I'm not sure.

Anyway, setting the volume to 0 seems to be the safest option at the moment. You can also do it in the constructor call itself:

```js
const audioMotion = new AudioMotionAnalyzer(container, {
    audioCtx: myApp.player.audioContext,
    source: myApp.player.outputNode,
    volume: 0,
});
```

**Comment by evoyy** [comment]
I discovered that same thing last night while experimenting with `disconnectOutput()`.

Setting the volume to 0 in the constructor actually solves my situation perfectly fine, there's no need to make any enhancements actually.

I have also been thinking about integrating audioMotion as a permantent part of my player at the output, and calling `toggleAnalyzer()` when opening/closing the analyzer modal.

I will close this issue, as there isn't any issue really. Once I have this working in my app I'll send you a link so you can check it out.

**Comment by hvianna** [comment]
> Once I have this working in my app I'll send you a link so you can check it out.

Please do! I'd love to see it!

I just found some reference on this behavior at https://bugs.chromium.org/p/chromium/issues/detail?id=1045926#c13

> This is different from how AnalyserNode works which works "magically".  If the output is not connected, it get processed.  If it's connected to the destination, it get processed.  **However, if it's connected to another node but isn't connected to the destination, the node doesn't work.**

The problem is that audioMotion's analyzer nodes are connected to a gain node and this node is connected to the destination. When I disconnect the gain node from the destination, the analyzer is still connected to it and, per Chromium specifications, it stops working.

I'll have a look to see if I can solve this without complicating things too much, as I would really like to have `disconnectOutput()` working for all browsers.

**Comment by hvianna** [comment]
So I went with `connectSpeakers` in the constructor options to be more specific and `disconnectOutput()` is now working properly on Chromium. 

Updated package is available in the beta tag on npm. Stable release should come later this week.

**Comment by evoyy** [comment]
Thanks, I will try that option. For now, though, I have already deployed the analyzer into production using the previous workaround.

Here is my website: https://mixolicious.com/

If you play a track, the spectrum analyzer icon will light up in the header and you can click on it to open the modal. I tried to keep it minimal with just a few controls.

**Comment by hvianna** [comment]
Awesome job on the site!!
A small suggestion: the tracks seem to be recorded pretty loud, so maybe you wanna increase the `maxDecibels` setting to -20 or -15 so the low frequency bars don't get capped.

**Comment by evoyy** [comment]
Thanks. It's not that they were recorded loud, but that many of them are compressed using a limiter. I think your maxDecibels suggestion is a nice idea and I will try that.
