### ISSUE TITLE
Radial mode not working?

### ISSUE THREAD

**Issue by lexterror** [hvianna/audioMotion-analyzer#14]
Hi I tried using "radial: true" and it doesnt work. There is no playback either.

**Comment by lexterror** [comment]
It's working now, but I had to change the default value in the js file!

Thank you!

**Comment by ianrothmann** [comment]
Hi @lexterror, I'm having the exact same issue. It works, but when I switch to radial it just doesn't render any audio. What did you do to fix this exactly? I've tried overriding defaults in the library with no luck.

Will appreciate your help!

**Comment by hvianna** [comment]
I've found the bug. Will fix this ASAP.
