### ISSUE TITLE
Same visualization in two different elements?

### ISSUE THREAD

**Issue by lexterror** [hvianna/audioMotion-analyzer#15]
I wanted to know if I could have the same visualization in two different divs?

**Comment by hvianna** [comment]
You'll need to create two instances:

```
let audioMotion = [];

audioMotion[0] = new AudioMotionAnalyzer( document.getElementById('container0'), {
    source: document.getElementById('audio'),
});

audioMotion[1] = new AudioMotionAnalyzer( document.getElementById('container1'), {
    source: audioMotion[0].connectedSources[0],
    connectSpeakers: false
});
```

See the [multi-instance demo source code](https://github.com/hvianna/audioMotion-analyzer/blob/master/demo/multi.js) for more details.

Live [Codepen](https://codepen.io/hvianna/pen/ExZmRwM)

**Comment by lexterror** [comment]
I have the above code: now I'm having some issues with the following:

      audioMotion[0].connectInput( player1.audioElement );

How do I add audioMotion[1] after the line above?
