### ISSUE TITLE
Use without canvas

### ISSUE THREAD

**Issue by davay42** [hvianna/audioMotion-analyzer#19]
I want to use the library in my vue js project. I need the 1/12 octave bands get generated out of the fft data, but I'm going to visualize them with reactive svg. So I just need the bars on evey onCanvasDraw, but I don't need a canvas.

I'm using it in a composable function, so I don't want to create a hidden canvas. Is there an option to totally omit canvas?

So we can use the lib as simple as that:
```
  const audioMotion = new AudioMotionAnalyzer(null, {
    source: chain.analyse,
    onCanvasDraw: analyse,
  })

  function analyse(AM) {
    state.bars = AM.bars  // state is reactive and is the carrier to get the data to the UI
  }
```

**Comment by hvianna** [comment]
Hello! 

There's no way to do it right now. The canvas is a key element in the code and its dimensions even affect the amount of detail you get out of the FFT in the discrete frequencies mode. Also, the bar values (amplitudes) are not currently stored in the _bars property; they're calculated inside the draw function, used and thrown away.

But it shouldn't be too much trouble to get around this, so let me see what I can do!

**Comment by davay42** [comment]
Thanks! I'm looking for a way to separate pitch classes in the spectrum, so we could see each not as a separate bar (roughly). I think 1/12 octave bars could be a good place to start. Some tweaking and tuning may be needed, of course )

**Comment by hvianna** [comment]
So, it took me longer than expected due to some personal stuff, but I just pushed a beta version to npm and updated the develop branch - please check the [changelog](https://github.com/hvianna/audioMotion-analyzer/blob/develop/Changelog.md) for documentation on the new property and method.

I also created a [live pen](https://codepen.io/hvianna/pen/ZEKWWJb) with example usage.

**Comment by davay42** [comment]
Wow! That's great news! I'll try it soon!

Yet, there's a problem with the pen. The divs are updating, but with height: 0. Tested with the file and with the stream on Firefox and Google on macOs. Here's the video

https://user-images.githubusercontent.com/6184449/124704427-baada880-defc-11eb-99e5-8183380cd745.mov

**Comment by hvianna** [comment]
That's weird.. I tested it on two versions of macOS and it works on every browser except for Safari. Do you hear any sound?

**Comment by davay42** [comment]
Strangely it started working! And it works amazing! The spectrum is so easy readable even for complex sound. The only thing left is a way to get the exact frequencies for each bar. Like as with Tone.js FFT https://tonejs.github.io/docs/14.7.77/FFT#getFrequencyOfIndex

**Comment by hvianna** [comment]
Nice! The objects returned by [`getBars()`](https://github.com/hvianna/audioMotion-analyzer/blob/develop/README.md#getbars) contain the starting and ending frequencies for each bar.

**Comment by hvianna** [comment]
This is now available is [version 3.5.0](https://github.com/hvianna/audioMotion-analyzer/releases/tag/3.5.0)

**Comment by davay42** [comment]
@hvianna Hey! I just wanted to say thank you for the great update! It got so easy to use! With just a couple of lines of code I've managed to build a realtime color spectrogram, that shows the exact notes and overtone frequencies in color! That's so mesmerizing to watch an interact with! Check it out here https://chromatone.center/practice/pitch/spectrogram.html ✊✌️👍

**Comment by hvianna** [comment]
@davay42 Thanks for the follow-up. Awesome job!! 🚀
