### ISSUE TITLE
Typescript error when building with angular project: Version 3.5.0

### ISSUE THREAD

**Issue by puhazh** [hvianna/audioMotion-analyzer#20]
Version: 3.5.0
Last known working version: 3.3.0

When using audiomotion-analyzer in an angular project, running dist to pack for production fails with the following error.

`ERROR in node_modules/audiomotion-analyzer/src/index.d.ts:53:23 - error TS1005: ',' expected.

53   hold: [ mono_or_left: number, right?: number ];`

Reverted to 3.3.0 and it is working fine.

**Comment by hvianna** [comment]
What is your TypeScript version? Looks like it's not properly detecting the labeled tuples, which is a TS 4.0+ feature.

**Comment by puhazh** [comment]
@hvianna Ah got it, I am on Angular 9 and the TypeScript version is 3.7.5. Looks like maximum supported version of TypeScript in Angular 9 is 3.9.0.

`ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0`

**Comment by hvianna** [comment]
@puhazh I didn't mean this to be a restriction, so I removed the labeled tuples in [version 3.5.1](https://github.com/hvianna/audioMotion-analyzer/releases/tag/3.5.1)

**Comment by puhazh** [comment]
@hvianna Thank you.
