### ISSUE TITLE
Support: Is it possible to change visualization color during play?

### ISSUE THREAD

**Issue by lexterror** [hvianna/audioMotion-analyzer#21]
Hi, hvianna!!!

I'm trying to change the hsl color while the stream is playing! Thank you for your past support! I just need to know how to approach changing the color!

I'm trying to do:

    audioMotion.options = {

		// Gradient definitions
			gradients: {
			classic: {
				bgColor: '#000',
				colorStops: [
				 // 'hsl( 0, 100%, 50% )',
				'hsl( 0, 0%, 100% )',
		
				 // 'hsl( 29, 100%, 50% )',
					hslcolor,
				]
			},
		}
		}

Thank you!

I also tried: 
               audioMotion.options.gradients {}

I'm trying to access: audioMotion -> options -> gradients

**Comment by hvianna** [comment]
Hello,

You can update the gradient using the [`registerGradient()`](https://audiomotion.dev/#/?id=registergradient-name-options-) method, like so:

```js
audioMotion.registerGradient( 'classic', {
  bgColor: '#000',
  colorStops: [
    'hsl( 0, 0%, 100% )',
    hslcolor,
  ]
});
```

Whenever you do this, you'll also need to re-set the current gradient, so audioMotion will apply the changes, like so:

```js
audioMotion.gradient = 'classic';
```

For the next version, I'll update the code so this last step won't be necessary any longer.

**Comment by lexterror** [comment]
Hi, hvianna!!!

It worked great!!! Thank you so much for your help, it means a lot to me! You can check out my player here: http://elounge.org

I'm not a pro in Javascript (that's one of my problems) but I try!!!

Thank you hvianna!!!
