### ISSUE TITLE
[Question] Is there a way to connect multiple audio elements to a visualizer, or maybe the final AudioDestinationNode?

### ISSUE THREAD

**Issue by adityakrshnn** [hvianna/audioMotion-analyzer#46]
Hi,

Great Project I must say! I wanted to ask if we can connect multiple audio elements to the visualizer, or maybe the final AudioDestinationNode of the speaker? I want the visualier to be a sum of all the media (including videos) running on the website.

Thanks

**Comment by adityakrshnn** [comment]
I found a way to do it. You can use a GainNode to connect multiple audio sources to it and then attach it to `audioMotion` https://codepen.io/adityakrshnn/pen/abRPXvw

**Comment by hvianna** [comment]
You can connect additional sources after instantiation with [`connectInput()`](https://audiomotion.dev/#/?id=connectinput-source-)
