### ISSUE TITLE
[Question] Can we seek and draw audio visualizer on a particular time?

### ISSUE THREAD

**Issue by adityakrshnn** [hvianna/audioMotion-analyzer#47]
Hi,

Can we draw frames of the audio visualizer and let it stay on that? I am trying to export the audio visualizer as a video file. For that, I need the ability to seek the audio visualizer at particular times and wait so that I can capture a screenshot. I can see there is an `onCanvasDraw` callback, however, is there any way to make it draw the visualizer with the exact preset that I have set on `audiomotion` object?

**Comment by hvianna** [comment]
Let's please use Discussions for this. https://github.com/hvianna/audioMotion-analyzer/discussions/48
