### ISSUE TITLE
Google chrome won't play the audio. It works on other browsers.

### ISSUE THREAD

**Issue by lexterror** [hvianna/audioMotion-analyzer#6]
Hi, I'm getting the following error on Google Chrome:

"Uncaught (in promise) DOMException: The play() request was interrupted by a new load request"

It won't play after I click the button. I'm forced to go site:settings on chrome to enable audio. However the stream URLs play if I don't use AudioMotion Analyzer.

It only happens on google chrome. Is there a fix or workaround I can try?

Thank you!

**Comment by hvianna** [comment]
Hello! Can you share the code you're using for playback?

**Comment by lexterror** [comment]
The link is http://elounge.org (view source in any browser)

**Comment by lexterror** [comment]
<div id="container2" class="fluid"></div>
--
  | <div id="lcd-container2" class="lcd-container">
  | </div>
  | <audio id="audio" autoplay loop controls crossorigin="anonymous" src="">
  | </audio>
  |  
  |  
  |  
  | <script src="fluid.js"></script>

**Comment by lexterror** [comment]
<div id="container2" class="fluid"></div>
    <div id="lcd-container2" class="lcd-container">
    </div>
	<audio id="audio" autoplay loop controls crossorigin="anonymous" src="">
	</audio><script src="fluid.js"></script>

**Comment by lexterror** [comment]
It's ok (I'm actually busy right now)

Thank you for your help!

**Comment by hvianna** [comment]
You don't need to include the bundled `fluid.js` file. Here's a simpler code that I can confirm works on Chrome:

In your HTML file:

```
<body>
  <div id="container"></div>
  <audio id="audio" src="http://94.130.113.214:8000/chill" controls crossorigin="anonymous"></audio>

  <!-- the type="module" below is important - note this works only when loaded via HTTP, not in local file:// mode -->
  <script src="analyzer.js" type="module"></script>
</body>
```

The `analyzer.js` file:

```
// get the audioMotion-analyzer.js file from the project's "src" folder
import AudioMotionAnalyzer from 'audioMotion-analyzer.js';

try {
  var audioMotion = new AudioMotionAnalyzer(
    document.getElementById('container'),
      {
        source: document.getElementById('audio'),
        // set your preferred options here
      }
  );
}
catch( err ) {
  document.getElementById('container').innerHTML = `<p>audioMotion-analyzer failed with error: <em>${err}</em></p>`;
}

// Resume audio context if in suspended state (browsers' autoplay policy)
window.addEventListener( 'click', () => {
  if ( audioMotion.audioCtx.state == 'suspended' )
    audioMotion.audioCtx.resume();
});

**Comment by hvianna** [comment]
@lexterror I edited my previous comment with simpler code.
