### ISSUE TITLE
Precedence of gradient, gradientLeft and gradientRight in setOptions()

### ISSUE THREAD

**Issue by Staijn1** [hvianna/audioMotion-analyzer#60]
Hi there!

I'm implementing a new feature in my application that creates and sets a new gradient, with the colors of the album cover of the song you are listening to in Spotify.
In this application, the visualizer options are stored with Redux, meaning I don't have direct control of what the order is of attributes within this object.

To show that the order of attributes in the options object matter, I've created the following codepen based on the Microphone Input demo: [https://codepen.io/Staijn1/pen/QWzPNLq](https://codepen.io/Staijn1/pen/QWzPNLq)

In this codepen you can see two functions that set the `gradient` property. 
One function sets the gradientLeft _before_ the gradient, resulting in both channels being updated.
The other function sets the gradientLeft _after_ the gradient property, resulting in only the right channel being updated because the `gradientLeft` overwrites the value set by `gradient`.

I fixed my issue by setting gradientLeft and gradientRight to undefined so they will not interfere, because I can't control the order of attributes due to redux. This would be another solution.

In hindsight this is a pretty obvious issue but it still took me some time. That's why I created this issue to discuss if anything can be done to make this more explicit. Maybe by documenting or extending the API (but I'm not sure what this would look like).

I'd love to hear your thoughts.

Greetings,
Stein

**Comment by Staijn1** [comment]
Update: My fix was not actually sufficient.
Setting gradientLeft and gradientRight to undefined results in an error about the gradient not being found, which is interesting.

Instead, I now delete the gradientLeft and gradientRight attributes using the `delete` keyword:
```typescript
// Register gradient here obviously
this.visualizerOptions.gradient = "spotify";
delete this.visualizerOptions.gradientLeft;
delete this.visualizerOptions.gradientRight;
// Dispatch the redux store change here, which will trigger a call to audiomotion.setOptions(options) somewhere
```

ps, Absolutely love this library, it is truly amazing and I use it daily. I'll buy you some coffee.

**Comment by hvianna** [comment]
Hello @Staijn1!

Maybe I'm missing something here, but have you tried setting only `gradientLeft` and `gradientRight` in your options object? You don't need to define a value for `gradient`, unless you want to use the same gradient on both channels.

> ps, Absolutely love this library, it is truly amazing and I use it daily. I'll buy you some coffee.

Thanks a lot! I really **really** appreciate the support and feedback! ❤️🙏

Also, how do you integrate with Spotify? 👀 Is your application a browser extension?

**Comment by Staijn1** [comment]
Hi!

Good shout, I will check that out. Sometimes you are so focused on the problem you can't see the simple fixes anymore.. Thanks haha

About spotify: 
The integration with Spotify was quite easy. Spotify provides multiple API's, one of which is the Playback SDK. With this SDK you can create a spotify player in your browser. It will then show up as a device in the spotify app.

A working version of my app can be found at https://demo.phos.steinjonker.nl/ on the visualizer page. Open the settings panel by clicking the left button in the top toolbar and select the spotify tab.
After logging in you are redirected to the home page, so go back to the visualizer. I'm working on redirecting you to the visualizer page automatically.

Then select the device from the Spotify app and there it goes!

I completed a PR within my own repo yesterday that completed the work on this, it can be found [here](https://github.com/Staijn1/angulon/pull/158/files). But for easier viewing, I'd recommend to just look at the source files. The files that are changes are the only pieces of code that are involved with this functionality.

**Comment by hvianna** [comment]
Cool, thanks for the info! Angulon is looking awesome!

**Comment by Staijn1** [comment]
Suggested fix of not using gradient at all works, closing this issue.

Thanks!

**Comment by jeadys** [comment]
> Hi!
> 
> Good shout, I will check that out. Sometimes you are so focused on the problem you can't see the simple fixes anymore.. Thanks haha
> 
> About spotify: The integration with Spotify was quite easy. Spotify provides multiple API's, one of which is the Playback SDK. With this SDK you can create a spotify player in your browser. It will then show up as a device in the spotify app.
> 
> A working version of my app can be found at https://demo.phos.steinjonker.nl/ on the visualizer page. Open the settings panel by clicking the left button in the top toolbar and select the spotify tab. After logging in you are redirected to the home page, so go back to the visualizer. I'm working on redirecting you to the visualizer page automatically.
> 
> Then select the device from the Spotify app and there it goes!
> 
> I completed a PR within my own repo yesterday that completed the work on this, it can be found [here](https://github.com/Staijn1/angulon/pull/158/files). But for easier viewing, I'd recommend to just look at the source files. The files that are changes are the only pieces of code that are involved with this functionality.

Hey, I see you ask for microphone permission in order to setup the audio stream from Spotify to motion analyzer, why is this? (probably project specific). Do you happen to know how I could stream my currently played spotify song to motion analyzer without asking for extra permissions? I tried setting connectSpeakres to true to visualize whatever is playing, but it doesn't seem to work. (btw I'm visualizing stuff in the browser). 

I also tried messing around with the source attribute but this won't work with the track uri I get back from the Spotify API. Only thing that seems to work is using the preview_url from a track to get a 30 second mp3 file.
