### ISSUE TITLE
[Feature Request] It would be great if the demo has a copy as options button

### ISSUE THREAD

**Issue by biigpongsatorn** [hvianna/audioMotion-analyzer#62]
I've just play around the demo (https://audiomotion.dev/demo/fluid.html), And I think it would be great if it has a copy to`options` object and I can paste the option into my code :)

**Comment by hvianna** [comment]
Will do!

**Comment by hvianna** [comment]
Now available in [v4.4.0](https://github.com/hvianna/audioMotion-analyzer/releases/tag/4.4.0) 🚀
