### ISSUE TITLE
2 Feature Requests: Let user decide the size of the circle / use existing canvas

### ISSUE THREAD

**Issue by orangecoding** [hvianna/audioMotion-analyzer#63]
Hey,

- if I chose to display a radial visualization, I'd like to be able to tell how big the circle actually is
- I'd like to connect audioMotion to a canvas, which I define by myself rather than letting your lib creating it

I think those 2 optionals would make sense to be added, wdyt?

Thanks
Chriz

**Comment by hvianna** [comment]
Yeah, let's do this!

**Comment by hvianna** [comment]
Now available in [v4.4.0](https://github.com/hvianna/audioMotion-analyzer/releases/tag/4.4.0) 🚀

**Comment by orangecoding** [comment]
Thanks mate
