### ISSUE TITLE
Wrong typing or documentation about `GradientOptions.bgcolor`

### ISSUE THREAD

**Issue by jgabriel98** [hvianna/audioMotion-analyzer#82]
Readme documentation about [`registerGradient`](https://github.com/hvianna/audioMotion-analyzer/blob/master/src/index.d.ts#L111) says the bgcolor is optional: ![image](https://github.com/user-attachments/assets/60c953b6-7631-4fef-831b-0fed0a0b9d6d)

but the [`GradientOptions` type definition](https://github.com/hvianna/audioMotion-analyzer/blob/master/src/index.d.ts#L111) says otherwise: 
![image](https://github.com/user-attachments/assets/1bb1bd49-61f8-4bcb-b220-7e3bbaee30f2)

**Comment by hvianna** [comment]
The type definition is incorrect. It will be fixed in the next release. Thanks for reporting this.

**Comment by jgabriel98** [comment]
Sure! no problem!

If you don't mind me taking your attention, 
could you help me out with a [question i posted on discussions](https://github.com/hvianna/audioMotion-analyzer/discussions/83)? i'm really stuck 😢 .

If not is still okay! thanks for this amazing software anyways!
