### ISSUE TITLE
Audio Feedback loop when using a stream

### ISSUE THREAD

**Issue by Hakeem-star** [hvianna/audioMotion-analyzer#9]
Whenever I try to get audio from a stream, there is awful feedback which made this unusable.

I recreated this problem on [this sandbox](https://codesandbox.io/s/bold-hill-zi2w9?file=/index.html).

**You'll need to make sure you select "Share Audio" in the popup.**

I managed to fix it for my use case by removing line 91 - 

`		this._analyzer.connect( this._audioCtx.destination );
`

but I'm sure this would have broken some other use case.

I'm far from an expert when it comes to the audio API but it looked like we were feeding the audio back into itself?

There wasn't much really any examples for integrating with streams in the docs as well, so it would have been great if we had a stream implementation example in the docs. 

**Thank you very much for the work you've done one this by the way. It's sure to make my life easier!**

**Comment by hvianna** [comment]
Hello! Yes, when using a microphone stream you should disconnect the analyzer from the speakers to prevent feedback.

You can use the line below in your code:
```
AudioMotion.analyzer.disconnect( AudioMotion.audioCtx.destination );
```

Version 3.0.0 (currently in beta) will provide a handy `volume` property, which you can set to 0 to prevent feedback loops.
If you want to try it, `npm i audiomotion-analyzer@beta` - please be aware of some [breaking changes](https://github.com/hvianna/audioMotion-analyzer/tree/develop#about)

I'll try to improve the docs and implementation examples. Thanks for your feedback!
